# Generated by Django 4.2.30 on 2026-08-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('status', models.CharField(default='non_lu', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('program', 'Programmes'), ('activity', 'Activités'), ('news', 'Actualités'), ('formation', 'Formations'), ('media', 'Médias'), ('team', 'Équipe'), ('testimonial', 'Témoignages'), ('user', 'Utilisateurs')], max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('instructor_name', models.CharField(blank=True, max_length=120)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('registered_seats', models.PositiveIntegerField(default=0)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('archive', 'Archivé'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='publie', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['order', '-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('archive', 'Archivé'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='publie', max_length=20)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('partner_type', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('archive', 'Archivé'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='actif', max_length=20)),
                ('featured_home', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.TextField(blank=True)),
                ('group', models.CharField(default='general', max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('archive', 'Archivé'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('archive', 'Archivé'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.contentitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
