# Generated by Django 4.2.30 on 2026-08-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_multilingual_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['order', '-date', '-created_at'], 'verbose_name': 'Élément de contenu', 'verbose_name_plural': 'Éléments de contenu'},
        ),
        migrations.AlterModelOptions(
            name='formationregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inscription formation', 'verbose_name_plural': 'Inscriptions formations'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['slug'], 'verbose_name': 'Contenu de page', 'verbose_name_plural': 'Contenus de pages'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Paramètre du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidature bénévole', 'verbose_name_plural': 'Candidatures bénévoles'},
        ),
        migrations.AddField(
            model_name='contentitem',
            name='body_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='category_fr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='instructor_name_ar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='instructor_name_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='instructor_name_fr',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='location_ar',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='location_en',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='location_fr',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='meta_description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='summary_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='title_fr',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='meta_description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='subtitle_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='title_fr',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='body_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='category_ar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='category_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='keywords_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='summary_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title_ar',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='keywords_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='subtitle_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title_ar',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title_en',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_ar',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
