# Generated by Django 4.2.30 on 2026-08-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_fr_translation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('programme', 'Programmé'), ('archive', 'Archivé'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to='core.contentitem')),
            ],
            options={
                'verbose_name': 'Inscription activité',
                'verbose_name_plural': 'Inscriptions activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
