# Generated by Django 4.2.30 on 2026-08-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activityregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
