# Generated by Django 4.2.30 on 2026-08-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_facebook_url_partner_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
