# Generated by Django 4.2.30 on 2026-08-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partner_linkedin_url_partner_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
