# Generated by Django 4.2.30 on 2026-08-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_partner_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
