# Generated by Django 4.2.30 on 2026-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contentitem_linkedin_url_contentitem_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='cv_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
