# Generated by Django 4.2.30 on 2026-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_volunteerapplication_cv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='desired_fields',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='skills_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
