# Generated by Django 4.2.30 on 2026-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_volunteerapplication_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
