from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = "dashboard"


def protected(view):
    return login_required(view, login_url="dashboard:login")


urlpatterns = [
    path("login/", views.dashboard_login, name="login"),
    path("logout/", views.dashboard_logout, name="logout"),
    path("", protected(views.dashboard), name="home"),
    path("home-page/", protected(views.home_page_management), name="home_page"),
    path("notification-counts/", protected(views.dashboard_notification_counts), name="notification_counts"),
    path("home-announcements/<int:pk>/update/", protected(views.home_announcement_update), name="home_announcement_update"),
    path("site-content/", protected(views.site_content), name="site_content"),
    path("site-content/<slug:slug>/edit/", protected(views.page_edit), name="page_edit"),
    path("about/", protected(views.about_list), name="about"),
    path("about/edit/", protected(views.about_edit), name="about_edit"),
    path("programs/", protected(lambda request, key="program": views.module_list(request, key)), name="program_list"),
    path("programs/add/", protected(lambda request, key="program": views.module_form(request, key)), name="program_add"),
    path("programs/<int:pk>/edit/", protected(lambda request, pk, key="program": views.module_form(request, key, pk=pk, edit=True)), name="program_edit"),
    path("programs/<int:pk>/", protected(lambda request, pk, key="program": views.module_detail(request, key, pk=pk)), name="program_detail"),
    path("activities/", protected(lambda request, key="activity": views.module_list(request, key)), name="activity_list"),
    path("activities/add/", protected(lambda request, key="activity": views.module_form(request, key)), name="activity_add"),
    path("activities/<int:pk>/edit/", protected(lambda request, pk, key="activity": views.module_form(request, key, pk=pk, edit=True)), name="activity_edit"),
    path("activities/<int:pk>/", protected(lambda request, pk, key="activity": views.module_detail(request, key, pk=pk)), name="activity_detail"),
    path("news/", protected(lambda request, key="news": views.module_list(request, key)), name="news_list"),
    path("news/add/", protected(lambda request, key="news": views.module_form(request, key)), name="news_add"),
    path("news/<int:pk>/edit/", protected(lambda request, pk, key="news": views.module_form(request, key, pk=pk, edit=True)), name="news_edit"),
    path("news/<int:pk>/", protected(lambda request, pk, key="news": views.module_detail(request, key, pk=pk)), name="news_detail"),
    path("formations/", protected(lambda request, key="formation": views.module_list(request, key)), name="formation_list"),
    path("formations/add/", protected(lambda request, key="formation": views.module_form(request, key)), name="formation_add"),
    path("formations/<int:pk>/edit/", protected(lambda request, pk, key="formation": views.module_form(request, key, pk=pk, edit=True)), name="formation_edit"),
    path("formations/<int:pk>/", protected(lambda request, pk, key="formation": views.module_detail(request, key, pk=pk)), name="formation_detail"),
    path("registrations/", protected(lambda request, key="registration": views.module_list(request, key)), name="registration_list"),
    path("registrations/add/", protected(lambda request, key="registration": views.module_form(request, key)), name="registration_add"),
    path("registrations/<int:pk>/edit/", protected(lambda request, pk, key="registration": views.module_form(request, key, pk=pk, edit=True)), name="registration_edit"),
    path("registrations/<int:pk>/", protected(lambda request, pk, key="registration": views.module_detail(request, key, pk=pk)), name="registration_detail"),
    path("registrations/<str:key>/<int:pk>/status/", protected(views.update_registration_status), name="update_registration_status"),
    path("activity-registrations/", protected(lambda request, key="activity_registration": views.module_list(request, key)), name="activity_registration_list"),
    path("activity-registrations/add/", protected(lambda request, key="activity_registration": views.module_form(request, key)), name="activity_registration_add"),
    path("activity-registrations/<int:pk>/edit/", protected(lambda request, pk, key="activity_registration": views.module_form(request, key, pk=pk, edit=True)), name="activity_registration_edit"),
    path("activity-registrations/<int:pk>/", protected(lambda request, pk, key="activity_registration": views.module_detail(request, key, pk=pk)), name="activity_registration_detail"),
    path("media/", protected(lambda request, key="media": views.module_list(request, key)), name="media_list"),
    path("media/add/", protected(lambda request, key="media": views.module_form(request, key)), name="media_add"),
    path("media/<int:pk>/edit/", protected(lambda request, pk, key="media": views.module_form(request, key, pk=pk, edit=True)), name="media_edit"),
    path("media/<int:pk>/", protected(lambda request, pk, key="media": views.module_detail(request, key, pk=pk)), name="media_detail"),
    path("volunteers/", protected(lambda request, key="volunteer": views.module_list(request, key)), name="volunteer_list"),
    path("volunteers/add/", protected(lambda request, key="volunteer": views.module_form(request, key)), name="volunteer_add"),
    path("volunteers/<int:pk>/edit/", protected(lambda request, pk, key="volunteer": views.module_form(request, key, pk=pk, edit=True)), name="volunteer_edit"),
    path("volunteers/<int:pk>/", protected(lambda request, pk, key="volunteer": views.module_detail(request, key, pk=pk)), name="volunteer_detail"),
    path("contacts/", protected(lambda request, key="contact": views.module_list(request, key)), name="contact_messages"),
    path("contacts/add/", protected(lambda request, key="contact": views.module_form(request, key)), name="contact_add"),
    path("contacts/<int:pk>/edit/", protected(lambda request, pk, key="contact": views.module_form(request, key, pk=pk, edit=True)), name="contact_edit"),
    path("contacts/<int:pk>/", protected(lambda request, pk, key="contact": views.module_detail(request, key, pk=pk)), name="contact_detail"),
    path("partners/", protected(lambda request, key="partner": views.module_list(request, key)), name="partner_list"),
    path("partners/add/", protected(lambda request, key="partner": views.module_form(request, key)), name="partner_add"),
    path("partners/<int:pk>/edit/", protected(lambda request, pk, key="partner": views.module_form(request, key, pk=pk, edit=True)), name="partner_edit"),
    path("partners/<int:pk>/", protected(lambda request, pk, key="partner": views.module_detail(request, key, pk=pk)), name="partner_detail"),
    path("team/", protected(lambda request, key="team": views.module_list(request, key)), name="team_list"),
    path("team/add/", protected(lambda request, key="team": views.module_form(request, key)), name="team_add"),
    path("team/<int:pk>/edit/", protected(lambda request, pk, key="team": views.module_form(request, key, pk=pk, edit=True)), name="team_edit"),
    path("team/<int:pk>/", protected(lambda request, pk, key="team": views.module_detail(request, key, pk=pk)), name="team_detail"),
    path("testimonials/", protected(lambda request, key="testimonial": views.module_list(request, key)), name="testimonial_list"),
    path("testimonials/add/", protected(lambda request, key="testimonial": views.module_form(request, key)), name="testimonial_add"),
    path("testimonials/<int:pk>/edit/", protected(lambda request, pk, key="testimonial": views.module_form(request, key, pk=pk, edit=True)), name="testimonial_edit"),
    path("testimonials/<int:pk>/", protected(lambda request, pk, key="testimonial": views.module_detail(request, key, pk=pk)), name="testimonial_detail"),
    path("users/", protected(lambda request, key="user": views.module_list(request, key)), name="user_list"),
    path("users/add/", protected(lambda request, key="user": views.module_form(request, key)), name="user_add"),
    path("users/<int:pk>/edit/", protected(lambda request, pk, key="user": views.module_form(request, key, pk=pk, edit=True)), name="user_edit"),
    path("users/<int:pk>/", protected(lambda request, pk, key="user": views.module_detail(request, key, pk=pk)), name="user_detail"),
    path("module-delete/<str:key>/<int:pk>/", protected(views.module_delete), name="module_delete"),
    path("module-duplicate/<str:key>/<int:pk>/", protected(views.module_duplicate), name="module_duplicate"),
    path("settings/", protected(views.settings_page), name="settings"),
    path("translate-api/", protected(views.translate_api_view), name="translate_api"),
    path("settings/<int:pk>/edit/", protected(views.setting_edit), name="setting_edit"),
    path("settings/<int:pk>/delete/", protected(views.setting_delete), name="setting_delete"),
    path("profile/", protected(views.profile), name="profile"),
]
