def language_context(request):
    from core.views import site_settings, get_language_code
    lang = get_language_code(request)

    if lang == "ar":
        ui = {
            "about": 'عن المؤسسة',
            "programme": 'البرامج والأنشطة',
            "activities": 'الأنشطة',
            "news": 'المستجدات',
            "formations": 'الدورات التكوينية',
            "media": 'معرض الوسائط',
            "volunteering": 'التطوع',
            "contact": 'اتصل بنا',
            "join_us": 'انضم إلينا',
            "discover_foundation": 'اكتشف المؤسسة',
            "become_volunteer": 'كن متطوعاً',
            "scroll": 'التمرير',
            "announcements": 'الأخبار والإعلانات',
            "read_more": 'اقرأ المزيد',
            "read_article": 'اقرأ المقال',
            "featured": 'الرئيسية',
            "no_announcement": 'تابعونا لمعرفة آخر المستجدات',
            "add_news_dashboard": 'سنقوم بنشر أخبارنا ومستجداتنا هنا قريباً. ترقبوا المزيد!',
            "beneficiaries": 'المستفيدين',
            "direct_indirect": 'المباشرين وغير المباشرين',
            "programs": 'البرامج',
            "published": 'منشورة',
            "formations_published": 'تكوينات منشورة',
            "partners": 'الشركاء',
            "active": 'النشطين',
            "volunteers": 'المتطوعين',
            "applications": 'طلبات التطوع',
            "years": 'سنوات',
            "experience": 'من العطاء والخبرة',
            "domains": 'مجالات تدخلنا',
            "discover": 'اكتشف',
            "no_program": 'لا يوجد أي برنامج منشور حالياً.',
            "foundation_activities": 'أنشطة المؤسسة',
            "all_activities": 'عرض جميع الأنشطة',
            "our_partners": 'شركاؤنا',
            "volunteer_intro": 'انضم إلى مجتمع ديناميكي يغير طنجة. كل بادرة تساهم في بناء مستقبل أفضل.',
            "mission_1": 'مهام مرنة تناسب وقتك وتخصصك',
            "mission_2": 'دورات تدريبية لتطوير مهاراتك الشخصية',
            "mission_3": 'أثر ملموس على تنمية المجتمع',
            "register_now": 'سجل الآن',
            "contact_us": 'اتصل بنا',
            "full_name": 'الاسم الكامل',
            "email": 'البريد الإلكتروني',
            "your_message": 'رسالتك',
            "send": 'إرسال الرسالة',
            "programs_published": 'البرامج المنشورة',
            "team": 'فريق العمل',
            "no_team": 'لا يوجد أي عضو منشور من لوحة التحكم.',
            "quick_links": 'روابط سريعة',
            "coordinates": 'معلومات الاتصال',
            "social_networks": 'شبكات التواصل',
            "subscribe": 'اشترك الآن',
            "all_rights": 'جميع الحقوق محفوظة.',
            "back_top": 'الأعلى',
            "language": 'اللغة',
            "home": 'الرئيسية',
            # UI labels for frontend JS
            "register": "تسجيل",
            "location": "المكان",
            "participants": "مشاركين",
            "no_report": "لا توجد تقارير متاحة",
            "one_report": "تقرير واحد متاح",
            "reports_available": "تقارير متاحة",
            "full_name_label": "الاسم الكامل *",
            "birth_date_label": "تاريخ الميلاد *",
            "email_label": "البريد الإلكتروني *",
            "phone_label": "الهاتف *",
            "city_label": "المدينة *",
            "study_level_label": "المستوى الدراسي",
            "motivation_label": "رسالة التحفيز",
            "accept_terms": "أوافق على شروط التسجيل *",
            "confirm_registration": "تأكيد التسجيل",
            "link_copied": "تم نسخ الرابط بنجاح !",
            "no_results_title": "لم يتم العثور على نتائج",
            "no_results_desc": "لا توجد عناصر تطابق معايير التصفية المحددة.",
            "reset_filters": "إعادة تعيين",
            "category_label": "التصنيف",
            "year_label": "السنة",
            "month_label": "الشهر",
            "search_placeholder": "البحث عن نشاط...",
            "all_categories": "جميع التصنيفات",
            "all_years": "جميع السنوات",
            "all_months": "جميع الأشهر",
            "sport": "رياضة",
            "culture": "ثقافة",
            "education": "تعليم",
            "social": "تضامن",
        }
    elif lang == "en":
        ui = {
            "about": 'About',
            "programme": 'Program & Activities',
            "activities": 'Activities',
            "news": 'News',
            "formations": 'Formations',
            "media": 'Media Gallery',
            "volunteering": 'Volunteering',
            "contact": 'Contact',
            "join_us": 'Join Us',
            "discover_foundation": 'Discover the Foundation',
            "become_volunteer": 'Become a Volunteer',
            "scroll": 'Scroll',
            "announcements": 'News & Announcements',
            "read_more": 'Read More',
            "read_article": 'Read Article',
            "featured": 'Featured',
            "no_announcement": 'Stay Tuned for Our Latest News',
            "add_news_dashboard": 'We will publish our latest news, announcements, and events here soon.',
            "beneficiaries": 'Beneficiaries',
            "direct_indirect": 'direct and indirect',
            "programs": 'Programs',
            "published": 'published',
            "formations_published": 'formations published',
            "partners": 'Partners',
            "active": 'active',
            "volunteers": 'Volunteers',
            "applications": 'candidatures',
            "years": 'Years',
            "experience": 'of experience',
            "domains": 'Our Fields of Intervention',
            "discover": 'Discover',
            "no_program": 'No programs published at the moment.',
            "foundation_activities": 'Foundation Activities',
            "all_activities": 'See all activities',
            "our_partners": 'Our Partners',
            "volunteer_intro": 'Join a dynamic community transforming Tangier. Every action counts to build a better future.',
            "mission_1": 'Flexible missions matching your availability',
            "mission_2": 'Trainings offered to develop your skills',
            "mission_3": 'Measurable impact on the community',
            "register_now": 'Register Now',
            "contact_us": 'Contact Us',
            "full_name": 'Full name',
            "email": 'Email',
            "your_message": 'Your message',
            "send": 'Send Message',
            "programs_published": 'Programs published',
            "team": 'Team',
            "no_team": 'No members published from the dashboard.',
            "quick_links": 'Quick Links',
            "coordinates": 'Coordinates',
            "social_networks": 'Social Networks',
            "subscribe": 'Subscribe',
            "all_rights": 'All rights reserved.',
            "back_top": 'Top',
            "language": 'Language',
            "home": 'Home',
            # UI labels for frontend JS
            "register": "Register",
            "location": "Location",
            "participants": "participants",
            "no_report": "No reports available",
            "one_report": "1 report available",
            "reports_available": "reports available",
            "full_name_label": "Full name *",
            "birth_date_label": "Birth date *",
            "email_label": "Email *",
            "phone_label": "Phone *",
            "city_label": "City *",
            "study_level_label": "Study level",
            "motivation_label": "Motivation",
            "accept_terms": "I accept the registration conditions *",
            "confirm_registration": "Confirm my registration",
            "link_copied": "Link copied successfully!",
            "no_results_title": "No results found",
            "no_results_desc": "No items match the selected filters.",
            "reset_filters": "Reset",
            "category_label": "Category",
            "year_label": "Year",
            "month_label": "Month",
            "search_placeholder": "Search for an activity...",
            "all_categories": "All categories",
            "all_years": "All years",
            "all_months": "All months",
            "sport": "Sport",
            "culture": "Culture",
            "education": "Education",
            "social": "Social",
        }
    else: # default to French
        ui = {
            "about": 'À propos',
            "programme": 'Programme',
            "activities": 'Activités',
            "news": 'Actualités',
            "formations": 'Formations',
            "media": 'Médias',
            "volunteering": 'Bénévolat',
            "contact": 'Contact',
            "join_us": 'Rejoignez-nous',
            "discover_foundation": 'Découvrir la Fondation',
            "become_volunteer": 'Devenir Bénévole',
            "scroll": 'Défiler',
            "announcements": 'Actualités & Annonces',
            "read_more": 'Lire la suite',
            "read_article": "Lire l'article",
            "featured": 'À la une',
            "no_announcement": 'Restez connectés pour nos actualités',
            "add_news_dashboard": 'Nos dernières actualités et annonces seront publiées ici très prochainement.',
            "beneficiaries": 'Bénéficiaires',
            "direct_indirect": 'directs et indirects',
            "programs": 'Programmes',
            "published": 'publiés',
            "formations_published": 'publiées',
            "partners": 'Partenaires',
            "active": 'actifs',
            "volunteers": 'Bénévoles',
            "applications": 'candidatures',
            "years": 'Années',
            "experience": "d'expérience",
            "domains": "Nos Domaines d'Intervention",
            "discover": 'Découvrir',
            "no_program": 'Aucun programme publié pour le moment.',
            "foundation_activities": 'Activités de la Fondation',
            "all_activities": 'Voir toutes les activités',
            "our_partners": 'Nos Partenaires',
            "volunteer_intro": 'Rejoignez une communauté dynamique qui transforme Tanger. Chaque geste compte pour construire un avenir meilleur.',
            "mission_1": 'Missions flexibles adaptées à votre disponibilité',
            "mission_2": 'Formations offertes pour développer vos compétences',
            "mission_3": 'Impact mesurable sur la communauté',
            "register_now": "S'inscrire maintenant",
            "contact_us": 'Contactez-nous',
            "full_name": 'Nom complet',
            "email": 'Email',
            "your_message": 'Votre message',
            "send": 'Envoyer',
            "programs_published": 'Programmes publiés',
            "team": 'Équipe',
            "no_team": 'Aucun membre publié depuis le dashboard.',
            "quick_links": 'Liens rapides',
            "coordinates": 'Coordonnées',
            "social_networks": 'Réseaux sociaux',
            "subscribe": "S'abonner",
            "all_rights": 'Tous droits réservés.',
            "back_top": 'Haut',
            "language": 'Langue',
            "home": 'Accueil',
            # UI labels for frontend JS
            "register": "S'inscrire",
            "location": "Lieu",
            "participants": "participants",
            "no_report": "Aucun rapport disponible",
            "one_report": "1 rapport disponible",
            "reports_available": "rapports disponibles",
            "full_name_label": "Nom complet *",
            "birth_date_label": "Date de naissance *",
            "email_label": "Email *",
            "phone_label": "Téléphone *",
            "city_label": "Ville *",
            "study_level_label": "Niveau d'études",
            "motivation_label": "Motivation",
            "accept_terms": "J'accepte les conditions d'inscription *",
            "confirm_registration": "Confirmer mon inscription",
            "link_copied": "Lien copié avec succès !",
            "no_results_title": "Aucune activité trouvée",
            "no_results_desc": "Aucune activité ne correspond aux filtres sélectionnés.",
            "reset_filters": "Réinitialiser",
            "category_label": "Catégorie",
            "year_label": "Année",
            "month_label": "Mois",
            "search_placeholder": "Rechercher une activité...",
            "all_categories": "Toutes les catégories",
            "all_years": "Toutes les années",
            "all_months": "Tous les mois",
            "sport": "Sport",
            "culture": "Culture",
            "education": "Éducation",
            "social": "Social",
        }

    return {
        "brand_name": "Fondation Tanger Métropole",
        "current_language": lang,
        "text_direction": "rtl" if lang == "ar" else "ltr",
        "available_languages": [("fr", "Français"), ("ar", "العربية"), ("en", "English")],
        "ui": ui,
        "settings": site_settings(lang),
    }
